#!/bin/bash

# ******************************************************************************
# EOS - the CERN Disk Storage System
# Copyright (C) 2018 CERN/Switzerland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# ******************************************************************************

#------------------------------------------------------------------------------
# Description: Script testing the draining mechanism of EOS. It assumes that
#              there are at least 7 FSTs available in the instance.
#
# Usage:
# eos-drain-test <eos_mgm_hostname>
#------------------------------------------------------------------------------

# Helper cleanup method
cleanup() {
  eos rm -rF "${EOS_DRAIN_DIR}/replica/*"
  eos rm -rF "${EOS_DRAIN_DIR}/raiddp/*"
  eos rm -rF "${EOS_DRAIN_DIR}/rain/*"
  eos rmdir "${EOS_DRAIN_DIR}/replica/"
  eos rmdir "${EOS_DRAIN_DIR}/raiddp/"
  eos rmdir "${EOS_DRAIN_DIR}/rain/"
  eos rm -rF "${EOS_DRAIN_DIR}/recycle/*"
  eos recycle config --remove-bin "${EOS_DRAIN_DIR}/recycle/"
  eos rmdir "${EOS_DRAIN_DIR}/recycle/"
  eos rmdir "${EOS_DRAIN_DIR}/"
  rm -rf ${TEST_FN0} ${TEST_FN1} ${TEST_FN2}
}

# Wait for the drain of the given file system to end
wait_drain_end() {
  sleep 2

  while eos fs ls | grep " $1 " | grep -q "prepare\|waiting\|draining\|stalling"; do
    sleep 2
  done
}

# Start the drain of the given file system. A drain that just ended is only
# cleaned up by the drainer every 5 seconds, so retry until it is accepted.
start_drain() {
  for i in {1..15}; do
    eos fs config $1 configstatus=drain && return 0
    sleep 2
  done

  return 1
}

# Drain a file system holding a recycle-bin file while no other file system
# accepts writes, so the drain job of the file fails. The entry must be kept
# with space.drainer.purge.recycle=off and purged with it on.
test_drain_purge_recycle() {
  local dir="${EOS_DRAIN_DIR}/recycle/"
  local rc=0
  eos mkdir -p ${dir}
  eos chmod 2777 ${dir}
  eos attr set default=replica ${dir}
  eos attr set sys.forced.nstripes=1 ${dir}
  eos recycle config --add-bin ${dir}
  xrdcp -f --nopbar ${TEST_FN1} root://${EOS_MGM_HOSTNAME}/${dir}/purge.dat
  local fmd=$(eos fileinfo ${dir}/purge.dat -m | tr ' ' '\n')
  local fxid=$(echo "${fmd}" | grep "^fxid=" | cut -d= -f2)
  local fsid=$(echo "${fmd}" | grep "^fsid=" | cut -d= -f2)

  if [[ -z "${fsid}" ]]; then
    echo "error: failed to upload the recycle-bin test file"
    return 1
  fi

  eos rm ${dir}/purge.dat
  local all_fsids=$(eos fs ls -m | tr ' ' '\n' | grep "^id=" | cut -d= -f2)

  for i in ${all_fsids}; do
    [[ ${i} -ne ${fsid} ]] && eos fs config ${i} configstatus=ro
  done

  eos space config default space.drainer.purge.recycle=off
  start_drain ${fsid}
  wait_drain_end ${fsid}

  if ! eos fs dumpmd ${fsid} --fxid | grep -q "^fxid=${fxid}$"; then
    echo "error: recycle-bin entry fxid=${fxid} purged with the option off"
    rc=1
  fi

  eos fs config ${fsid} configstatus=rw
  eos space config default space.drainer.purge.recycle=on
  start_drain ${fsid}
  wait_drain_end ${fsid}

  if eos fs dumpmd ${fsid} --fxid | grep -q "^fxid=${fxid}$" ||
     eos recycle ls --all -m | grep -q "restore-key=fxid:0*${fxid} "; then
    echo "error: recycle-bin entry fxid=${fxid} not purged with the option on"
    rc=1
  fi

  eos space config default space.drainer.purge.recycle=off

  for i in ${all_fsids}; do
    eos fs config ${i} configstatus=rw
  done

  return ${rc}
}

if [[ $# -eq 0 || $# -gt 2 ]]; then
  echo "Usage: $0 <eos_mgm_hostname>"
  exit 1
fi

EOS_MGM_HOSTNAME=$1

# Check preconditions and make sure central draining is enabled
FST_ONLINE=$(eos fs ls | grep "online" | wc -l)

if [[ ${FST_ONLINE} -lt 7 ]]; then
  echo "error: not enough FSTs configured"
  exit 1
fi

# Create dummy test files
TEST_FN0=/var/tmp/zero.dat
TEST_FN1=/var/tmp/32kb.dat
TEST_FN2=/var/tmp/5mb.dat

touch ${TEST_FN0}
dd if=/dev/urandom of=${TEST_FN1} bs=1k count=32 &> /dev/null
dd if=/dev/urandom of=${TEST_FN2} bs=1M count=5  &> /dev/null

# Create eos directory for tests and copy some files in
EOS_DRAIN_DIR=/eos/dockertest/drain_test/
eos mkdir -p ${EOS_DRAIN_DIR}/replica/
eos mkdir -p ${EOS_DRAIN_DIR}/raiddp/
eos mkdir -p ${EOS_DRAIN_DIR}/rain/
eos chmod 2777 /eos/dockertest/
eos chmod 2777 ${EOS_DRAIN_DIR}/replica/
eos chmod 2777 ${EOS_DRAIN_DIR}/raiddp/
eos chmod 2777 ${EOS_DRAIN_DIR}/rain/
eos attr set default=replica ${EOS_DRAIN_DIR}/replica/
eos attr set default=raiddp ${EOS_DRAIN_DIR}/raiddp/
eos attr set default=raid6 ${EOS_DRAIN_DIR}/rain/
eos fs ls

for i in {1..4}; do
  xrdcp -f --nopbar ${TEST_FN0} root://${EOS_MGM_HOSTNAME}/${EOS_DRAIN_DIR}/replica/0kb_file${i}.dat
  xrdcp -f --nopbar ${TEST_FN0} root://${EOS_MGM_HOSTNAME}/${EOS_DRAIN_DIR}/raiddp/0kb_file${i}.dat
  xrdcp -f --nopbar ${TEST_FN0} root://${EOS_MGM_HOSTNAME}/${EOS_DRAIN_DIR}/rain/0kb_file${i}.dat
  xrdcp -f --nopbar ${TEST_FN1} root://${EOS_MGM_HOSTNAME}/${EOS_DRAIN_DIR}/replica/32kb_file${i}.dat
  xrdcp -f --nopbar ${TEST_FN1} root://${EOS_MGM_HOSTNAME}/${EOS_DRAIN_DIR}/raiddp/32kb_file${i}.dat
  xrdcp -f --nopbar ${TEST_FN1} root://${EOS_MGM_HOSTNAME}/${EOS_DRAIN_DIR}/rain/32kb_file${i}.dat
  xrdcp -f --nopbar ${TEST_FN2} root://${EOS_MGM_HOSTNAME}/${EOS_DRAIN_DIR}/replica/5mb_file${i}.dat
  xrdcp -f --nopbar ${TEST_FN2} root://${EOS_MGM_HOSTNAME}/${EOS_DRAIN_DIR}/raiddp/5mb_file${i}.dat
  xrdcp -f --nopbar ${TEST_FN2} root://${EOS_MGM_HOSTNAME}/${EOS_DRAIN_DIR}/rain/5mb_file${i}.dat
done

# Check that the file system is ready
eos fs ls | grep " 1 " | grep "rw" | grep "nodrain" | grep "online"

if [[ $? -ne 0 ]]; then
  echo "error: file system 1 is not online  ..."
  eos fs ls
  cleanup
  exit 1
fi

# Set all file systems in RO mode except for fsid 1 and 2 - then start a long
# running process which writes a file. The purpose is to test the draining of
# files being written when the draining is started.
for (( i=3; i<=${FST_ONLINE}; i++ )); do
  eos fs config $i configstatus=ro
done

# Start long running write operation which should select fsts 1 and 2 as destination
xrdcpslowwriter root://${EOS_MGM_HOSTNAME}/${EOS_DRAIN_DIR}/replica/slow_writer.dat &
xrdcpslowwriter_pid=$!
sleep 2

# Put back the rest of the file systems in rw mode so that the draining can
# select them as destination.
for (( i=3; i<=${FST_ONLINE}; i++ )); do
  eos fs config $i configstatus=rw
done

eos file info ${EOS_DRAIN_DIR}/replica/slow_writer.dat

# Start draining and wait for it to finish. Watch the drain column itself
# rather than the word "drain" anywhere in the row: the scheduling column that
# replaced configstatus reads "drain" only while the drain runs under the "ro"
# permissions, and every phase of a drain has to keep the loop going.
eos fs config 1 configstatus=drain
# Give the drain engine a moment to publish the initial status
sleep 2
eos fs ls | grep " 1 " | grep "prepare\|waiting\|draining\|stalling"

while [[ $? -eq 0 ]]; do
  sleep 2
  eos fs ls | grep " 1 " | grep "prepare\|waiting\|draining\|stalling"
done

eos fs ls # debug print on what the status is right now;
eos fs ls | grep " 1 " | grep "empty" | grep "drained"

if [[ $? -ne 0 ]]; then
  echo "error: file system 1 is not drained"
  echo "Current metadata content"
  eos fs dumpmd 1
  cleanup
  exit 1
else
  echo "File system 1 successfully drained"
fi

# Put back the file system in rw mode
eos fs config 1 configstatus=rw

if [[ $? -ne 0 ]]; then
  echo "error: failed to put file system in rw mode"
  cleanup
  exit 1
fi

# Wait for the slow writer to finish before clean-up
wait ${xrdcpslowwriter_pid}

if ! test_drain_purge_recycle; then
  cleanup
  exit 1
fi

cleanup
exit 0
