#!/bin/bash

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <mq_hostname>"
  exit 1
fi

MQ_HOST=$1
echo "Running MQ feeder-dumper test"

# Start dumper process
eos-mq-dumper root://${MQ_HOST}:1097//eos/test_fd 10 1000 20 &
PID_DUMPER=$!

# Allow the dumper to start fully
sleep 1

# Start feeder process
eos-mq-feeder root://${MQ_HOST}:1097//eos/test_fd 10 500

if [[ $? -ne 0 ]]; then
  echo "error: feeder failed"
  exit 1
fi

wait ${PID_DUMPER}

if [[ $? -ne 0 ]]; then
  echo "error: dumper failed"
  exit 1
fi

exit 0
