#!/bin/bash

# ******************************************************************************
# EOS - the CERN Disk Storage System
# Copyright (C) 2019 CERN/Switzerland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# ******************************************************************************

function usage() {
  echo "usage: $(basename $0) --type docker/k8s <k8s_namespace>"
  echo "       docker : script runs in a Docker based setup"
  echo "       k8s    : script runs in a Kubernetes setup and requires a namespace argument"
}

# Check minimal input
if [[ $# -lt 2 ]]; then
  echo "error: invalid number of arguments"
  usage
  exit 1
fi

# Running FSCK tests
echo "Runing FSCK tests ..."
eos-fsck-test "$@"

echo "Running MQ tests ..."
eos-mq-tests eos-mq-test.eoscluster.cern.ch

if [[ $? -ne 0 ]]; then
    echo "error: failed mq tests"
    exit 1
fi

echo "Running drain tests ..."
eos-drain-test localhost

if [[ $? -ne 0 ]]; then
    echo "error: failed drain test"
    exit 1
fi

echo "Running instance tests ..."
eos space quota default on
eos-instance-test

if [[ $? -ne 0 ]]; then
  cat /tmp/eos-instance-test/test-output.log
  exit 1
fi

eos space quota default off
exit 0
