#!/bin/bash

echo "Running drain test ..."
eos-drain-test localhost

if [[ $? -ne 0 ]]; then
    echo "Failed drain test"
    exit 1
fi

echo "Running instance test ..."
eos space quota default on
eos-instance-test

if [[ $? -ne 0 ]]; then
  cat /tmp/eos-instance-test/test-output.log
  exit 1
fi

eos space quota default off
exit 0
