#!/bin/bash
#
# eoshttpd        Startup script for the Apache HTTP Server for EOS gateways
#
# chkconfig: - 85 15
# description: Apache is a World Wide Web server.  It is used to serve \
#	       HTML files and CGI.
# processname: httpd
# config: /etc/httpd/conf/eoshttpd.conf
# config: /etc/sysconfig/eoshttpd
# pidfile: /var/run/eoshttpd.pid


# Source function library.
. /etc/rc.d/init.d/functions

if [ -f /etc/sysconfig/eoshttpd ]; then
        . /etc/sysconfig/eoshttpd
fi


export FULLSERVERNAME=`hostname -f`
# Copy back the default file and set the full qualified hostname in the config file
cp /etc/httpd/conf/eoshttpd.default.conf /etc/httpd/conf/eoshttpd.conf
perl -pi -e 's/FULLSERVERNAME/$ENV{FULLSERVERNAME}/' /etc/httpd/conf/eoshttpd.conf

# Fix permission
chown daemon:daemon /var/log/eos/httpd/
chown daemon:daemon /var/www/eos/cgi-bin/eos-httpd-redirector.cgi
chown daemon:daemon /var/www/eos/browser/connectors/jqueryFileTree.pl
chown root:daemon /var/www/eos/cgi-bin/eos-httpd-redirector-suexec.cgi
chmod 700 /var/www/eos/cgi-bin/eos-httpd-redirector.cgi
chmod 4750 /var/www/eos/cgi-bin/eos-httpd-redirector-suexec.cgi
chmod 700 /var/www/eos/browser/connectors/jqueryFileTree.pl
test -L /var/www/eos/eos || ln -s /eos /var/www/eos/eos
test -L /var/www/eos/browser/tree/eos || ln -s /eos /var/www/eos/browser/tree/eos

# Start httpd in the C locale by default.
HTTPD_LANG=${HTTPD_LANG-"C"}

# This will prevent initlog from swallowing up a pass-phrase prompt if
# mod_ssl needs a pass-phrase from the user.
INITLOG_ARGS=""

# Set HTTPD=/usr/sbin/httpd.worker in /etc/sysconfig/httpd to use a server
# with the thread-based "worker" MPM; BE WARNED that some modules may not
# work correctly with a thread-based MPM; notably PHP will refuse to start.

# Path to the apachectl script, server binary, and short-form for messages.
apachectl=/usr/sbin/apachectl
httpd=${HTTPD-/usr/sbin/httpd}
prog=httpd
pidfile=${PIDFILE-/var/run/eoshttpd.pid}
lockfile=${LOCKFILE-/var/lock/subsys/eoshttpd}
RETVAL=0
STOP_TIMEOUT=${STOP_TIMEOUT-10}

# check for 1.3 configuration
check13 () {
	CONFFILE=/etc/httpd/conf/eoshttpd.conf
	GONE="(ServerType|BindAddress|Port|AddModule|ClearModuleList|"
	GONE="${GONE}AgentLog|RefererLog|RefererIgnore|FancyIndexing|"
	GONE="${GONE}AccessConfig|ResourceConfig)"
	if LANG=C grep -Eiq "^[[:space:]]*($GONE)" $CONFFILE; then
		echo
		echo 1>&2 " Apache 1.3 configuration directives found"
		echo 1>&2 " please read /usr/share/doc/httpd-2.2.3/migration.html"
		failure "Apache 1.3 config directives test"
		echo
		exit 1
	fi
}

# The semantics of these two functions differ from the way apachectl does
# things -- attempting to start while running is a failure, and shutdown
# when not running is also a failure.  So we just do it the way init scripts
# are expected to behave here.
start() {
        echo -n $"Starting $prog: "
        check13 || exit 1
        LANG=$HTTPD_LANG daemon --pidfile=${pidfile} $httpd $OPTIONS
        RETVAL=$?
        echo
        [ $RETVAL = 0 ] && touch ${lockfile}
        return $RETVAL
}

# When stopping httpd a delay (of default 10 second) is required
# before SIGKILLing the httpd parent; this gives enough time for the
# httpd parent to SIGKILL any errant children.
stop() {
	echo -n $"Stopping $prog: "
	killproc -p ${pidfile} -d ${STOP_TIMEOUT} $httpd
	RETVAL=$?
	echo
	[ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
}
reload() {
    echo -n $"Reloading $prog: "
    if ! LANG=$HTTPD_LANG $httpd $OPTIONS -t >&/dev/null; then
        RETVAL=$?
        echo $"not reloading due to configuration syntax error"
        failure $"not reloading $httpd due to configuration syntax error"
    else
        killproc -p ${pidfile} $httpd -HUP
        RETVAL=$?
    fi
    echo
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
        status -p ${pidfile} $httpd
	RETVAL=$?
	;;
  restart)
	stop
	start
	;;
  condrestart)
	if [ -f ${pidfile} ] ; then
		stop
		start
	fi
	;;
  reload)
        reload
	;;
  graceful|help|configtest|fullstatus)
	$apachectl $@
	RETVAL=$?
	;;
  *)
	echo $"Usage: $prog {start|stop|restart|condrestart|reload|status|fullstatus|graceful|help|configtest}"
	exit 1
esac

exit $RETVAL
