#!/bin/bash
# ----------------------------------------------------------------------
# File: eos-iobw
# Author: Andreas-Joachim Peters - CERN
# ----------------------------------------------------------------------

# ************************************************************************
# * EOS - the CERN Disk Storage System                                   *
# * Copyright (C) 2011 CERN/Switzerland                                  *
# *                                                                      *
# * This program is free software: you can redistribute it and/or modify *
# * it under the terms of the GNU General Public License as published by *
# * the Free Software Foundation, either version 3 of the License, or    *
# * (at your option) any later version.                                  *
# *                                                                      *
# * This program is distributed in the hope that it will be useful,      *
# * but WITHOUT ANY WARRANTY; without even the implied warranty of       *
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        *
# * GNU General Public License for more details.                         *
# *                                                                      *
# * You should have received a copy of the GNU General Public License    *
# * along with this program.  If not, see <http://www.gnu.org/licenses/>.*
# ************************************************************************

# Usage: eos-iobw <path> => prints bandwidth in MB/s
test -z "$1"&& echo 0.00 && exit -1
path=`df $1 | tail -1 | awk '{print $1}'`
elapsed=`/usr/bin/time -f "%e" dd iflag=direct if=$path of=/dev/null bs=4M count=128 2>&1 | tail -1`
echo 512 $elapsed | awk '{ if ($2) {printf("%.02d\n", $1/$2)} else print "0.00"}'




