#!/bin/bash
. /etc/sysconfig/eos

/etc/init.d/eos status fst && exit -1
# you can add a --test to just simulate what would happen
# eosfstclean [--test] 

for fsname in `ls ${EOS_FST_DATA_DISK-/data}??/.eosfsid`; do
    fsid=`cat $fsname`;
    data=`dirname $fsname`;
    mdlog=`ls -1 ${EOS_FST_MD_LOCATION-/var/eos/md}/*.*$fsid.mdlog | sort | tail -1`;
    ${EOS_LOCATION-/usr}/sbin/eos-fst-fsck $mdlog --data=${data}/ --delete-missing-disk --cleanup-transactions $1
done

