// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IoBuffer.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_IoBuffer_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_IoBuffer_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_IoBuffer_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_IoBuffer_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_IoBuffer_2eproto;
namespace IoBuffer {
class Summary;
struct SummaryDefaultTypeInternal;
extern SummaryDefaultTypeInternal _Summary_default_instance_;
class data;
struct dataDefaultTypeInternal;
extern dataDefaultTypeInternal _data_default_instance_;
class data_AppsEntry_DoNotUse;
struct data_AppsEntry_DoNotUseDefaultTypeInternal;
extern data_AppsEntry_DoNotUseDefaultTypeInternal _data_AppsEntry_DoNotUse_default_instance_;
class data_GidsEntry_DoNotUse;
struct data_GidsEntry_DoNotUseDefaultTypeInternal;
extern data_GidsEntry_DoNotUseDefaultTypeInternal _data_GidsEntry_DoNotUse_default_instance_;
class data_UidsEntry_DoNotUse;
struct data_UidsEntry_DoNotUseDefaultTypeInternal;
extern data_UidsEntry_DoNotUseDefaultTypeInternal _data_UidsEntry_DoNotUse_default_instance_;
}  // namespace IoBuffer
PROTOBUF_NAMESPACE_OPEN
template <>
::IoBuffer::Summary* Arena::CreateMaybeMessage<::IoBuffer::Summary>(Arena*);
template <>
::IoBuffer::data* Arena::CreateMaybeMessage<::IoBuffer::data>(Arena*);
template <>
::IoBuffer::data_AppsEntry_DoNotUse* Arena::CreateMaybeMessage<::IoBuffer::data_AppsEntry_DoNotUse>(Arena*);
template <>
::IoBuffer::data_GidsEntry_DoNotUse* Arena::CreateMaybeMessage<::IoBuffer::data_GidsEntry_DoNotUse>(Arena*);
template <>
::IoBuffer::data_UidsEntry_DoNotUse* Arena::CreateMaybeMessage<::IoBuffer::data_UidsEntry_DoNotUse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace IoBuffer {

// ===================================================================


// -------------------------------------------------------------------

class Summary final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:IoBuffer.Summary) */ {
 public:
  inline Summary() : Summary(nullptr) {}
  ~Summary() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Summary(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Summary(const Summary& from);
  Summary(Summary&& from) noexcept
    : Summary() {
    *this = ::std::move(from);
  }

  inline Summary& operator=(const Summary& from) {
    CopyFrom(from);
    return *this;
  }
  inline Summary& operator=(Summary&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Summary& default_instance() {
    return *internal_default_instance();
  }
  static inline const Summary* internal_default_instance() {
    return reinterpret_cast<const Summary*>(
               &_Summary_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Summary& a, Summary& b) {
    a.Swap(&b);
  }
  inline void Swap(Summary* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Summary* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Summary* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Summary>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Summary& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Summary& from) {
    Summary::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Summary* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "IoBuffer.Summary";
  }
  protected:
  explicit Summary(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRAvrgFieldNumber = 1,
    kRStdFieldNumber = 2,
    kWAvrgFieldNumber = 3,
    kWStdFieldNumber = 4,
    kRSizeFieldNumber = 5,
    kWSizeFieldNumber = 6,
    kRIopsFieldNumber = 7,
    kWIopsFieldNumber = 8,
    kWinTimeFieldNumber = 9,
  };
  // optional uint32 rAvrg = 1;
  bool has_ravrg() const;
  void clear_ravrg() ;
  ::uint32_t ravrg() const;
  void set_ravrg(::uint32_t value);

  private:
  ::uint32_t _internal_ravrg() const;
  void _internal_set_ravrg(::uint32_t value);

  public:
  // optional uint32 rStd = 2;
  bool has_rstd() const;
  void clear_rstd() ;
  ::uint32_t rstd() const;
  void set_rstd(::uint32_t value);

  private:
  ::uint32_t _internal_rstd() const;
  void _internal_set_rstd(::uint32_t value);

  public:
  // optional uint32 wAvrg = 3;
  bool has_wavrg() const;
  void clear_wavrg() ;
  ::uint32_t wavrg() const;
  void set_wavrg(::uint32_t value);

  private:
  ::uint32_t _internal_wavrg() const;
  void _internal_set_wavrg(::uint32_t value);

  public:
  // optional uint32 wStd = 4;
  bool has_wstd() const;
  void clear_wstd() ;
  ::uint32_t wstd() const;
  void set_wstd(::uint32_t value);

  private:
  ::uint32_t _internal_wstd() const;
  void _internal_set_wstd(::uint32_t value);

  public:
  // uint32 rSize = 5;
  void clear_rsize() ;
  ::uint32_t rsize() const;
  void set_rsize(::uint32_t value);

  private:
  ::uint32_t _internal_rsize() const;
  void _internal_set_rsize(::uint32_t value);

  public:
  // uint32 wSize = 6;
  void clear_wsize() ;
  ::uint32_t wsize() const;
  void set_wsize(::uint32_t value);

  private:
  ::uint32_t _internal_wsize() const;
  void _internal_set_wsize(::uint32_t value);

  public:
  // double rIops = 7;
  void clear_riops() ;
  double riops() const;
  void set_riops(double value);

  private:
  double _internal_riops() const;
  void _internal_set_riops(double value);

  public:
  // double wIops = 8;
  void clear_wiops() ;
  double wiops() const;
  void set_wiops(double value);

  private:
  double _internal_wiops() const;
  void _internal_set_wiops(double value);

  public:
  // optional uint64 winTime = 9;
  bool has_wintime() const;
  void clear_wintime() ;
  ::uint64_t wintime() const;
  void set_wintime(::uint64_t value);

  private:
  ::uint64_t _internal_wintime() const;
  void _internal_set_wintime(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:IoBuffer.Summary)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::uint32_t ravrg_;
    ::uint32_t rstd_;
    ::uint32_t wavrg_;
    ::uint32_t wstd_;
    ::uint32_t rsize_;
    ::uint32_t wsize_;
    double riops_;
    double wiops_;
    ::uint64_t wintime_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_IoBuffer_2eproto;
};// -------------------------------------------------------------------

class data_AppsEntry_DoNotUse final : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<data_AppsEntry_DoNotUse, 
    std::string, ::IoBuffer::Summary,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<data_AppsEntry_DoNotUse, 
    std::string, ::IoBuffer::Summary,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  data_AppsEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR data_AppsEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit data_AppsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const data_AppsEntry_DoNotUse& other);
  static const data_AppsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const data_AppsEntry_DoNotUse*>(&_data_AppsEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "IoBuffer.data.AppsEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_IoBuffer_2eproto;
};
// -------------------------------------------------------------------

class data_UidsEntry_DoNotUse final : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<data_UidsEntry_DoNotUse, 
    ::uint64_t, ::IoBuffer::Summary,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT64,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<data_UidsEntry_DoNotUse, 
    ::uint64_t, ::IoBuffer::Summary,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT64,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  data_UidsEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR data_UidsEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit data_UidsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const data_UidsEntry_DoNotUse& other);
  static const data_UidsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const data_UidsEntry_DoNotUse*>(&_data_UidsEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_IoBuffer_2eproto;
};
// -------------------------------------------------------------------

class data_GidsEntry_DoNotUse final : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<data_GidsEntry_DoNotUse, 
    ::uint64_t, ::IoBuffer::Summary,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT64,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<data_GidsEntry_DoNotUse, 
    ::uint64_t, ::IoBuffer::Summary,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT64,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  data_GidsEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR data_GidsEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit data_GidsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const data_GidsEntry_DoNotUse& other);
  static const data_GidsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const data_GidsEntry_DoNotUse*>(&_data_GidsEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_IoBuffer_2eproto;
};
// -------------------------------------------------------------------

class data final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:IoBuffer.data) */ {
 public:
  inline data() : data(nullptr) {}
  ~data() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR data(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  data(const data& from);
  data(data&& from) noexcept
    : data() {
    *this = ::std::move(from);
  }

  inline data& operator=(const data& from) {
    CopyFrom(from);
    return *this;
  }
  inline data& operator=(data&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const data& default_instance() {
    return *internal_default_instance();
  }
  static inline const data* internal_default_instance() {
    return reinterpret_cast<const data*>(
               &_data_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(data& a, data& b) {
    a.Swap(&b);
  }
  inline void Swap(data* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(data* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  data* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<data>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const data& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const data& from) {
    data::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(data* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "IoBuffer.data";
  }
  protected:
  explicit data(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kAppsFieldNumber = 1,
    kUidsFieldNumber = 2,
    kGidsFieldNumber = 3,
  };
  // map<string, .IoBuffer.Summary> apps = 1;
  int apps_size() const;
  private:
  int _internal_apps_size() const;

  public:
  void clear_apps() ;
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::IoBuffer::Summary >&
      _internal_apps() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::IoBuffer::Summary >*
      _internal_mutable_apps();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::IoBuffer::Summary >&
      apps() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::IoBuffer::Summary >*
      mutable_apps();
  // map<uint64, .IoBuffer.Summary> uids = 2;
  int uids_size() const;
  private:
  int _internal_uids_size() const;

  public:
  void clear_uids() ;
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::uint64_t, ::IoBuffer::Summary >&
      _internal_uids() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::uint64_t, ::IoBuffer::Summary >*
      _internal_mutable_uids();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::uint64_t, ::IoBuffer::Summary >&
      uids() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::uint64_t, ::IoBuffer::Summary >*
      mutable_uids();
  // map<uint64, .IoBuffer.Summary> gids = 3;
  int gids_size() const;
  private:
  int _internal_gids_size() const;

  public:
  void clear_gids() ;
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::uint64_t, ::IoBuffer::Summary >&
      _internal_gids() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::uint64_t, ::IoBuffer::Summary >*
      _internal_mutable_gids();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::uint64_t, ::IoBuffer::Summary >&
      gids() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::uint64_t, ::IoBuffer::Summary >*
      mutable_gids();
  // @@protoc_insertion_point(class_scope:IoBuffer.data)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        data_AppsEntry_DoNotUse,
        std::string, ::IoBuffer::Summary,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> apps_;
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        data_UidsEntry_DoNotUse,
        ::uint64_t, ::IoBuffer::Summary,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT64,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> uids_;
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        data_GidsEntry_DoNotUse,
        ::uint64_t, ::IoBuffer::Summary,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT64,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> gids_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_IoBuffer_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Summary

// optional uint32 rAvrg = 1;
inline bool Summary::has_ravrg() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Summary::clear_ravrg() {
  _impl_.ravrg_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint32_t Summary::ravrg() const {
  // @@protoc_insertion_point(field_get:IoBuffer.Summary.rAvrg)
  return _internal_ravrg();
}
inline void Summary::set_ravrg(::uint32_t value) {
  _internal_set_ravrg(value);
  // @@protoc_insertion_point(field_set:IoBuffer.Summary.rAvrg)
}
inline ::uint32_t Summary::_internal_ravrg() const {
  return _impl_.ravrg_;
}
inline void Summary::_internal_set_ravrg(::uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.ravrg_ = value;
}

// optional uint32 rStd = 2;
inline bool Summary::has_rstd() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Summary::clear_rstd() {
  _impl_.rstd_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::uint32_t Summary::rstd() const {
  // @@protoc_insertion_point(field_get:IoBuffer.Summary.rStd)
  return _internal_rstd();
}
inline void Summary::set_rstd(::uint32_t value) {
  _internal_set_rstd(value);
  // @@protoc_insertion_point(field_set:IoBuffer.Summary.rStd)
}
inline ::uint32_t Summary::_internal_rstd() const {
  return _impl_.rstd_;
}
inline void Summary::_internal_set_rstd(::uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.rstd_ = value;
}

// optional uint32 wAvrg = 3;
inline bool Summary::has_wavrg() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void Summary::clear_wavrg() {
  _impl_.wavrg_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::uint32_t Summary::wavrg() const {
  // @@protoc_insertion_point(field_get:IoBuffer.Summary.wAvrg)
  return _internal_wavrg();
}
inline void Summary::set_wavrg(::uint32_t value) {
  _internal_set_wavrg(value);
  // @@protoc_insertion_point(field_set:IoBuffer.Summary.wAvrg)
}
inline ::uint32_t Summary::_internal_wavrg() const {
  return _impl_.wavrg_;
}
inline void Summary::_internal_set_wavrg(::uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.wavrg_ = value;
}

// optional uint32 wStd = 4;
inline bool Summary::has_wstd() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void Summary::clear_wstd() {
  _impl_.wstd_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::uint32_t Summary::wstd() const {
  // @@protoc_insertion_point(field_get:IoBuffer.Summary.wStd)
  return _internal_wstd();
}
inline void Summary::set_wstd(::uint32_t value) {
  _internal_set_wstd(value);
  // @@protoc_insertion_point(field_set:IoBuffer.Summary.wStd)
}
inline ::uint32_t Summary::_internal_wstd() const {
  return _impl_.wstd_;
}
inline void Summary::_internal_set_wstd(::uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.wstd_ = value;
}

// uint32 rSize = 5;
inline void Summary::clear_rsize() {
  _impl_.rsize_ = 0u;
}
inline ::uint32_t Summary::rsize() const {
  // @@protoc_insertion_point(field_get:IoBuffer.Summary.rSize)
  return _internal_rsize();
}
inline void Summary::set_rsize(::uint32_t value) {
  _internal_set_rsize(value);
  // @@protoc_insertion_point(field_set:IoBuffer.Summary.rSize)
}
inline ::uint32_t Summary::_internal_rsize() const {
  return _impl_.rsize_;
}
inline void Summary::_internal_set_rsize(::uint32_t value) {
  ;
  _impl_.rsize_ = value;
}

// uint32 wSize = 6;
inline void Summary::clear_wsize() {
  _impl_.wsize_ = 0u;
}
inline ::uint32_t Summary::wsize() const {
  // @@protoc_insertion_point(field_get:IoBuffer.Summary.wSize)
  return _internal_wsize();
}
inline void Summary::set_wsize(::uint32_t value) {
  _internal_set_wsize(value);
  // @@protoc_insertion_point(field_set:IoBuffer.Summary.wSize)
}
inline ::uint32_t Summary::_internal_wsize() const {
  return _impl_.wsize_;
}
inline void Summary::_internal_set_wsize(::uint32_t value) {
  ;
  _impl_.wsize_ = value;
}

// double rIops = 7;
inline void Summary::clear_riops() {
  _impl_.riops_ = 0;
}
inline double Summary::riops() const {
  // @@protoc_insertion_point(field_get:IoBuffer.Summary.rIops)
  return _internal_riops();
}
inline void Summary::set_riops(double value) {
  _internal_set_riops(value);
  // @@protoc_insertion_point(field_set:IoBuffer.Summary.rIops)
}
inline double Summary::_internal_riops() const {
  return _impl_.riops_;
}
inline void Summary::_internal_set_riops(double value) {
  ;
  _impl_.riops_ = value;
}

// double wIops = 8;
inline void Summary::clear_wiops() {
  _impl_.wiops_ = 0;
}
inline double Summary::wiops() const {
  // @@protoc_insertion_point(field_get:IoBuffer.Summary.wIops)
  return _internal_wiops();
}
inline void Summary::set_wiops(double value) {
  _internal_set_wiops(value);
  // @@protoc_insertion_point(field_set:IoBuffer.Summary.wIops)
}
inline double Summary::_internal_wiops() const {
  return _impl_.wiops_;
}
inline void Summary::_internal_set_wiops(double value) {
  ;
  _impl_.wiops_ = value;
}

// optional uint64 winTime = 9;
inline bool Summary::has_wintime() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void Summary::clear_wintime() {
  _impl_.wintime_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::uint64_t Summary::wintime() const {
  // @@protoc_insertion_point(field_get:IoBuffer.Summary.winTime)
  return _internal_wintime();
}
inline void Summary::set_wintime(::uint64_t value) {
  _internal_set_wintime(value);
  // @@protoc_insertion_point(field_set:IoBuffer.Summary.winTime)
}
inline ::uint64_t Summary::_internal_wintime() const {
  return _impl_.wintime_;
}
inline void Summary::_internal_set_wintime(::uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.wintime_ = value;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// data

// map<string, .IoBuffer.Summary> apps = 1;
inline int data::_internal_apps_size() const {
  return _impl_.apps_.size();
}
inline int data::apps_size() const {
  return _internal_apps_size();
}
inline void data::clear_apps() {
  _impl_.apps_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::IoBuffer::Summary >&
data::_internal_apps() const {
  return _impl_.apps_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::IoBuffer::Summary >&
data::apps() const {
  // @@protoc_insertion_point(field_map:IoBuffer.data.apps)
  return _internal_apps();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::IoBuffer::Summary >*
data::_internal_mutable_apps() {
  return _impl_.apps_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::IoBuffer::Summary >*
data::mutable_apps() {
  // @@protoc_insertion_point(field_mutable_map:IoBuffer.data.apps)
  return _internal_mutable_apps();
}

// map<uint64, .IoBuffer.Summary> uids = 2;
inline int data::_internal_uids_size() const {
  return _impl_.uids_.size();
}
inline int data::uids_size() const {
  return _internal_uids_size();
}
inline void data::clear_uids() {
  _impl_.uids_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::uint64_t, ::IoBuffer::Summary >&
data::_internal_uids() const {
  return _impl_.uids_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::uint64_t, ::IoBuffer::Summary >&
data::uids() const {
  // @@protoc_insertion_point(field_map:IoBuffer.data.uids)
  return _internal_uids();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::uint64_t, ::IoBuffer::Summary >*
data::_internal_mutable_uids() {
  return _impl_.uids_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::uint64_t, ::IoBuffer::Summary >*
data::mutable_uids() {
  // @@protoc_insertion_point(field_mutable_map:IoBuffer.data.uids)
  return _internal_mutable_uids();
}

// map<uint64, .IoBuffer.Summary> gids = 3;
inline int data::_internal_gids_size() const {
  return _impl_.gids_.size();
}
inline int data::gids_size() const {
  return _internal_gids_size();
}
inline void data::clear_gids() {
  _impl_.gids_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::uint64_t, ::IoBuffer::Summary >&
data::_internal_gids() const {
  return _impl_.gids_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::uint64_t, ::IoBuffer::Summary >&
data::gids() const {
  // @@protoc_insertion_point(field_map:IoBuffer.data.gids)
  return _internal_gids();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::uint64_t, ::IoBuffer::Summary >*
data::_internal_mutable_gids() {
  return _impl_.gids_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::uint64_t, ::IoBuffer::Summary >*
data::mutable_gids() {
  // @@protoc_insertion_point(field_mutable_map:IoBuffer.data.gids)
  return _internal_mutable_gids();
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace IoBuffer


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_IoBuffer_2eproto_2epb_2eh
