#!/bin/bash
. /etc/sysconfig/eos

if [ "x$1" = "x" ] ; then
# input parameter is the path to query e.g. eos-srm-checksum <file-path>
    echo "usage: eos-srm-checksum <filepath>"
    exit -1;
fi

chksum=`getfattr --only-values -n user.eos.XS $1 2>/dev/null | tr -d ' ' | cut -c -8`
echo $chksum