#!/bin/bash
# input parameter is the path to query e.g. eossrmspace /eos/atlas/
. /etc/sysconfig/eos
dirpath="${1%/}/"

path=`echo .eossrmspace.$dirpath | sed s/\\\//_/g`;
cache=`find /tmp/ -cmin 1 -name $path 2>/dev/null`;

if [ -n "$cache" ]; then
    cat $cache
    exit;
fi
    
nrep=`eos -b root://${EOS_FUSE_MGM_ALIAS-eosdev.cern.ch}// attr get sys.forced.nstripes $dirpath/ 2>/dev/null | grep sys.forced.nstripes | cut -d "=" -f2 | sed s/\"//g 2>/dev/null`

test -z "$nrep" && nrep=1

export `eos -b root://${EOS_FUSE_MGM_ALIAS-eosdev.cern.ch//}// quota ls -m -s $dirpath | grep "gid=ALL"`

val=$usedbytes

if [ $nrep -gt 1 ]; then 
    let val/=$nrep
fi

test -z $val && val=0

echo $val > /tmp/$path.tmp
mv /tmp/$path.tmp /tmp/$path 2>/dev/null
echo $val




