//------------------------------------------------------------------------------
// File: GroupBalancer.cc
// Author: Joaquim Rocha - CERN
//------------------------------------------------------------------------------

/************************************************************************
 * EOS - the CERN Disk Storage System                                   *
 * Copyright (C) 2011 CERN/Switzerland                                  *
 *                                                                      *
 * This program is free software: you can redistribute it and/or modify *
 * it under the terms of the GNU General Public License as published by *
 * the Free Software Foundation, either version 3 of the License, or    *
 * (at your option) any later version.                                  *
 *                                                                      *
 * This program is distributed in the hope that it will be useful,      *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of       *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        *
 * GNU General Public License for more details.                         *
 *                                                                      *
 * You should have received a copy of the GNU General Public License    *
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.*
 ************************************************************************/

#include "mgm/groupbalancer/GroupBalancer.hh"
#include "common/Constants.hh"
#include "common/FileId.hh"
#include "common/StringConversion.hh"
#include "common/utils/RandUtils.hh"
#include "mgm/convert/ConverterEngine.hh"
#include "mgm/fsview/FsView.hh"
#include "mgm/groupbalancer/BalancerEngineFactory.hh"
#include "mgm/groupbalancer/BalancerEngineUtils.hh"
#include "mgm/groupbalancer/ConverterUtils.hh"
#include "mgm/groupbalancer/GroupsInfoFetcher.hh"
#include "mgm/ofs/XrdMgmOfs.hh"
#include "namespace/interface/IFsView.hh"

#define CACHE_LIFE_TIME 60 // seconds

EOSMGMNAMESPACE_BEGIN

using group_balancer::BalancerEngineT;
using group_balancer::group_size_map;
using group_balancer::eosGroupsInfoFetcher;
using group_balancer::PrefixFilter;
static constexpr auto GROUPBALANCER_THREAD_NAME = "GroupBalancer";

//-------------------------------------------------------------------------------
// GroupBalancer constructor
//-------------------------------------------------------------------------------
GroupBalancer::GroupBalancer(const char* spacename)
  : mSpaceName(spacename), mLastCheck(0),
    mProcFilter(PrefixFilter(gOFS->MgmProcPath.c_str()))
{
  mEngine.reset(group_balancer::make_balancer_engine(BalancerEngineT::stddev));
  mThread.reset(&GroupBalancer::GroupBalance, this);
}

//------------------------------------------------------------------------------
// Stop group balancing thread
//------------------------------------------------------------------------------
void
GroupBalancer::Stop()
{
  mThread.join();
}

//------------------------------------------------------------------------------
// Destructor
//------------------------------------------------------------------------------
GroupBalancer::~GroupBalancer()
{
  Stop();
  mEngine->clear();
}

//------------------------------------------------------------------------------
// Update the list of ongoing transfers
//------------------------------------------------------------------------------
void
GroupBalancer::UpdateTransferList()
{
  for (auto it = mTransfers.begin(); it != mTransfers.end();) {
    if (!gOFS->mFidTracker.HasEntry(it->first)) {
      mTransfers.erase(it++);
    } else {
      ++it;
    }
  }

  eos_static_info("msg=\"group_balancer update transfers\" "
                  "scheduledtransfers=%d", mTransfers.size());
}

//------------------------------------------------------------------------------
// Creates the conversion file in proc for the file ID, from the given
// sourceGroup, to the targetGroup (and updates the cache structures)
//------------------------------------------------------------------------------
void
GroupBalancer::scheduleTransfer(const FileInfo& file_info, const std::string& sourceGroup,
                                const std::string& targetGroup)
{
  if (sourceGroup.empty() || targetGroup.empty()) {
    return;
  }

  auto mGroupSizes = mEngine->get_group_sizes();

  if ((mGroupSizes.count(sourceGroup) == 0) || (mGroupSizes.count(targetGroup) == 0)) {
    eos_static_err("msg=\"no src/trg group in map\" src_group=%s trg_group=%s",
                   sourceGroup.c_str(), targetGroup.c_str());
    return;
  }

  // Proc file name is generated by getFileProcTransferNameAndSize
  // doesn't contain (+) so we can append without checking
  std::string conv_tag = file_info.filename;
  conv_tag += "^";
  conv_tag += eos::common::EOS_APP_GROUP_BALANCER;
  conv_tag += "^";
  conv_tag.erase(0, gOFS->MgmProcConversionPath.length() + 1);
  std::string err_msg;

  if (gOFS->mConverterEngine->ScheduleJob(file_info.fid, conv_tag, err_msg)) {
    eos_static_info("msg=\"group balancer scheduled job\" file=\"%s\" "
                    "src_grp=\"%s\" dst_grp=\"%s\"",
                    conv_tag.c_str(), sourceGroup.c_str(), targetGroup.c_str());
  } else {
    eos_static_err("msg=\"group balancer could not schedule job\" "
                   "file=\"%s\" src_grp=\"%s\" dst_grp=\"%s\"",
                   conv_tag.c_str(), sourceGroup.c_str(), targetGroup.c_str());
  }

  mTransfers[file_info.fid] = file_info.filename;
}

//------------------------------------------------------------------------------
// Chooses a random file ID from a random filesystem in the given group
//------------------------------------------------------------------------------
eos::common::FileId::fileid_t
GroupBalancer::chooseFidFromGroup(const std::string& group_name)
{
  int rndIndex;
  bool found = false;
  eos::common::FileSystem::fsid_t fsid = 0;
  // Snapshot the eligible file systems. The FsGroup object is owned by the
  // FsView which can delete it at any moment, therefore it is looked up by
  // name and dereferenced only while holding the FsView lock. This is also
  // the only step that requires the lock and it does no I/O at all.
  std::vector<eos::common::FileSystem::fsid_t> candidates;
  {
    eos::common::RWMutexReadLock vlock(FsView::gFsView.ViewMutex);
    auto group_it = FsView::gFsView.mGroupView.find(group_name);

    if (group_it == FsView::gFsView.mGroupView.end()) {
      eos_static_info("msg=\"group no longer in the FsView\" group=\"%s\"",
                      group_name.c_str());
      return {};
    }

    const FsGroup* group = group_it->second;
    candidates.reserve(group->size());

    for (auto it = group->begin(); it != group->end(); ++it) {
      // Accept only active file systems
      FileSystem* target = FsView::gFsView.mIdView.lookupByID(*it);

      if (target && (target->GetActiveStatus() == eos::common::ActiveStatus::kOnline)) {
        candidates.push_back(*it);
      }
    }
  }

  // The namespace calls below can block for a long time - a SCARD round-trip
  // to QuarkDB, or even a full file list load taking tens of seconds - and
  // must therefore never run while holding the FsView lock, otherwise any
  // pending writer and all the readers queued behind it are stalled too.
  while (candidates.size() > 0) {
    rndIndex = common::getRandom(0ul, candidates.size() - 1);
    fsid = candidates[rndIndex];

    if (gOFS->eosFsView->getNumFilesOnFs(fsid)) {
      found = true;
      break;
    }

    candidates.erase(candidates.begin() + rndIndex);
  }

  // Check if we have any files to transfer
  if (!found) {
    return {};
  }

  int attempts = 10;

  while (attempts-- > 0) {
    eos::IFileMD::id_t randomPick;

    if (gOFS->eosFsView->getApproximatelyRandomFileInFs(fsid, randomPick) &&
        mTransfers.count(randomPick) == 0) {
      return randomPick;
    }
  }

  return {};
}

GroupBalancer::FileInfo
GroupBalancer::chooseFileFromGroup(const std::string& from_group,
                                   const std::string& to_group, int attempts)
{
  if (from_group.empty() || to_group.empty()) {
    return {};
  }

  uint64_t filesize;

  while (attempts-- > 0) {
    auto fid = chooseFidFromGroup(from_group);

    if (!fid) {
      continue;
    }

    auto filename = group_balancer::getFileProcTransferNameAndSize(
        fid, to_group, &filesize, mProcFilter);

    if (filename.empty() ||
        (mCfg.mMinFileSize > filesize) ||
        (mCfg.mMaxFileSize < filesize)) {
      continue;
    }

    // We've a hit!
    return {fid, std::move(filename), filesize};
  }

  return {};
}

//------------------------------------------------------------------------------
// Print size
//------------------------------------------------------------------------------
static void
printSizes(const group_size_map& group_sizes)
{
  for (const auto& it : group_sizes)
    eos_static_debug("group=%s average=%.02f", it.first.c_str(),
                     (double)it.second.filled() * 100.0);
}

//------------------------------------------------------------------------------
// Picks two groups (source and target) randomly and schedule a file ID
// to be transferred
//------------------------------------------------------------------------------
void
GroupBalancer::prepareTransfer()
{
  // Note that the groups are handled by name all the way down. The FsGroup
  // objects are owned by the FsView and must not be dereferenced outside of
  // the FsView lock, therefore they are looked up by name in the places that
  // do hold the lock.
  auto&& [over_it, under_it] = mEngine->pickGroupsforTransfer();

  if (over_it.empty() || under_it.empty()) {
    eos_static_info("msg=\"engine gave us empty groups skipping\" "
                    "engine_status=%s",
                    mEngine->get_status_str(false, true).c_str());
    return;
  }

  auto file_info = chooseFileFromGroup(over_it, under_it, mCfg.file_attempts);

  if (!file_info) {
    eos_static_info("msg=\"failed to choose any fid to schedule\" "
                    "failedgroup=%s",
                    over_it.c_str());
    return;
  }

  scheduleTransfer(file_info, over_it, under_it);
}

//------------------------------------------------------------------------------
// Check if the sizes cache should be updated (based on the time passed since
// they were last updated)
//------------------------------------------------------------------------------
bool
GroupBalancer::cacheExpired()
{
  time_t currentTime = time(NULL);

  if (difftime(currentTime, mLastCheck) > CACHE_LIFE_TIME) {
    mLastCheck = currentTime;
    return true;
  }

  return false;
}

//------------------------------------------------------------------------------
// Schedule a pre-defined number of transfers
//------------------------------------------------------------------------------
void
GroupBalancer::prepareTransfers(int nrTransfers)
{
  int allowedTransfers = nrTransfers - mTransfers.size();

  for (int i = 0; i < allowedTransfers; i++) {
    prepareTransfer();
  }

  if (allowedTransfers > 0) {
    printSizes(mEngine->get_group_sizes());
  }
}

std::string
GroupBalancer::Status(bool detail, bool monitoring) const
{
  eos::common::RWMutexReadLock lock(mEngineMtx);
  return mEngine->get_status_str(detail, monitoring);
}

bool
GroupBalancer::is_valid_engine(std::string_view engine_name)
{
  return engine_name == "std" || engine_name == "minmax" ||
         engine_name == "freespace";
}

//------------------------------------------------------------------------------
// Appply configuration stored at the space level
//------------------------------------------------------------------------------
bool
GroupBalancer::Configure(FsSpace* const space, GroupBalancer::Config& cfg)
{
  cfg.is_enabled = space->GetConfigMember("groupbalancer") == "on";
  cfg.is_conv_enabled = false;

  if (gOFS && gOFS->mConverterEngine &&
      gOFS->mConverterEngine->IsRunning()) {
    cfg.is_conv_enabled = true;
  }

  if (!cfg.is_enabled || !cfg.is_conv_enabled) {
    eos_static_info("msg=\"group balancer or converter not enabled\""
                    " space=%s balancer_status=%d converter_status=%d",
                    mSpaceName.c_str(), cfg.is_enabled, cfg.is_conv_enabled);
    return false;
  }

  cfg.num_tx = atoi(space->GetConfigMember("groupbalancer.ntx").c_str());
  cfg.mMinFileSize = common::StringConversion::GetSizeFromString(
                       space->GetConfigMember("groupbalancer.min_file_size"));
  cfg.mMaxFileSize = common::StringConversion::GetSizeFromString(
                       space->GetConfigMember("groupbalancer.max_file_size"));

  if (!cfg.mMaxFileSize) {
    eos_static_debug("%s", "msg=\"invalid Max File Size, using default\"");
    cfg.mMaxFileSize = GROUPBALANCER_MAX_FILE_SIZE;
  }

  cfg.engine_type = group_balancer::get_engine_type(
                      space->GetConfigMember("groupbalancer.engine"));
  cfg.file_attempts = atoi(
                        space->GetConfigMember("groupbalancer.file_attempts").c_str());

  if (!cfg.file_attempts) {
    eos_static_debug("%s", "msg=\"invalid File Attempts Count, using default\"");
    cfg.file_attempts = GROUPBALANCER_FILE_ATTEMPTS;
  }

  auto min_threshold_str = space->GetConfigMember("groupbalancer.min_threshold");
  auto max_threshold_str = space->GetConfigMember("groupbalancer.max_threshold");

  if (!group_balancer::is_valid_threshold(min_threshold_str, max_threshold_str)) {
    if (cfg.engine_type == BalancerEngineT::minmax) {
      eos_static_err("msg=\"invalid min/max balancer threshold configuration\""
                     " space=%s", mSpaceName.c_str());
      return false;
    }

    // This is a temporary stop gap until we force min/max threshold to be set
    // and remove this param. For std. balancer in case there isn't an explicit
    // min/max, let's set to configured threshold
    auto threshold_str = space->GetConfigMember("groupbalancer.threshold");

    if (!group_balancer::is_valid_threshold(threshold_str)) {
      eos_static_err("msg=\"invalid std balancer threshold configuration\""
                     " space=%s", mSpaceName.c_str());
      return false;
    }

    min_threshold_str = threshold_str;
    max_threshold_str = threshold_str;
  }

  auto blocklisted_groups = space->GetConfigMember("groupbalancer.blocklist");
  mEngineConf.insert_or_assign("min_threshold", std::move(min_threshold_str));
  mEngineConf.insert_or_assign("max_threshold", std::move(max_threshold_str));
  mEngineConf.insert_or_assign("blocklisted_groups",
                               std::move(blocklisted_groups));
  return true;
}


//------------------------------------------------------------------------------
// Eternal loop trying to run conversion jobs
//------------------------------------------------------------------------------
void
GroupBalancer::GroupBalance(ThreadAssistant& assistant) noexcept
{
  ThreadAssistant::setSelfThreadName(GROUPBALANCER_THREAD_NAME);
  gOFS->WaitUntilNamespaceIsBooted();
  eos_static_info("%s", "msg=\"starting group balancer thread\"");
  eosGroupsInfoFetcher fetcher(mSpaceName);
  group_balancer::BalancerEngineT prev_engine_type {BalancerEngineT::stddev};
  bool engine_reconfigured = false;
  bool config_status = true;

  // Loop forever until cancelled
  while (!assistant.terminationRequested()) {
    bool expected_reconfiguration = true;
    assistant.wait_for(std::chrono::seconds(10));

    if (!gOFS->mMaster->IsMaster()) {
      assistant.wait_for(std::chrono::seconds(10));
      eos_static_debug("%s", "msg=\"group balancer disabled for slave\"");
      continue;
    }

    // Try to read lock the mutex

    if (assistant.terminationRequested()) {
      return;
    }

    FsView::gFsView.ViewMutex.LockRead();

    if (!FsView::gFsView.mSpaceGroupView.count(mSpaceName.c_str())) {
      FsView::gFsView.ViewMutex.UnLockRead();
      eos_static_debug("msg=\"no groups to balance\" space=\"%s\"",
                       mSpaceName.c_str());
      break;
    }

    FsSpace* space = FsView::gFsView.mSpaceView[mSpaceName.c_str()];

    if (mDoConfigUpdate.compare_exchange_strong(expected_reconfiguration, false,
        std::memory_order_acq_rel)) {
      config_status = Configure(space, mCfg);
    }

    FsView::gFsView.ViewMutex.UnLockRead();
    // Update tracker for scheduled jobs
    gOFS->mFidTracker.DoCleanup(TrackerType::Convert);

    if (!gOFS->mConverterEngine || !config_status) {
      continue;
    }

    if (prev_engine_type != mCfg.engine_type) {
      mEngine.reset(group_balancer::make_balancer_engine(mCfg.engine_type));
      engine_reconfigured = true;
      prev_engine_type = mCfg.engine_type;
      fetcher.should_average(engine_should_average(mCfg.engine_type));
    }

    mEngine->configure(mEngineConf);
    UpdateTransferList();

    if ((int) mTransfers.size() >= mCfg.num_tx) {
      continue;
    }

    eos_static_debug("msg=\"group balancer enabled\" ntx=%d ", mCfg.num_tx);

    if (cacheExpired() || engine_reconfigured) {
      {
        eos::common::RWMutexWriteLock lock(mEngineMtx);
        mEngine->populateGroupsInfo(fetcher.fetch());
      }
      printSizes(mEngine->get_group_sizes());

      if (engine_reconfigured) {
        eos_static_info("msg=\"group balancer engine reconfigured\"");
        engine_reconfigured = false;
      }
    }

    if (!mEngine->canPick()) {
      eos_static_debug("msg=\"Empty source or target groups, cannot pick\""
                       " engine_status=%s",
                       mEngine->get_status_str(false, true).c_str());
      continue;
    }

    prepareTransfers(mCfg.num_tx);
  }
}

EOSMGMNAMESPACE_END
