FROM gitlab-registry.cern.ch/linuxsupport/slc6-base

LABEL maintainer="Fabio Luchetti, faluchet@cern.ch, CERN 2020"

WORKDIR /builds/dss/eos/

# if the working directory is a not the top-level dir of a git repo OR git remote is not set to the EOS repo url
RUN yum install --nogpg -y git \
    && if [[ $(git rev-parse --git-dir) != ".git" || $(git config --get remote.origin.url) != "https://gitlab.cern.ch/dss/eos.git" ]]; \
        then git clone https://gitlab.cern.ch/dss/eos.git . ; fi

RUN yum install --nogpg -y gcc-c++ cmake3 make rpm-build which git yum-plugin-priorities tar ccache sl-release-scl \
	&& source gitlab-ci/export_branch.sh \
    && echo "Exporting BRANCH=${BRANCH}" \
    && git submodule update --init --recursive \
    && ./misc/cmake/cmake-3.15.5-Linux-x86_64.sh --prefix=/usr/ --skip-license \
    && mkdir build \
    && cd build/ \
    && cmake3 ../ -DPACKAGEONLY=1 && make srpm \
    && cd ../ \
    && echo -e '[eos-depend]\nname=EOS dependencies\nbaseurl=http://storage-ci.web.cern.ch/storage-ci/eos/'${BRANCH}'-depend/el-6/x86_64/\ngpgcheck=0\nenabled=1\npriority=1\n' >> /etc/yum.repos.d/eos-depend.repo \
    && yum-builddep --nogpgcheck --setopt="cern*.exclude=xrootd*" -y build/SRPMS/* \
    && yum install -y moreutils \
    && yum clean all
# install moreutils just for 'ts', nice to benchmark the build time.
# cleaning yum cache should reduce image size.

ENTRYPOINT /bin/bash
