#!/bin/bash
# ----------------------------------------------------------------------
# File: eos-log-clean
# Author: Andreas-Joachim Peters - CERN
# ----------------------------------------------------------------------

# ************************************************************************
# * EOS - the CERN Disk Storage System                                   *
# * Copyright (C) 2011 CERN/Switzerland                                  *
# *                                                                      *
# * This program is free software: you can redistribute it and/or modify *
# * it under the terms of the GNU General Public License as published by *
# * the Free Software Foundation, either version 3 of the License, or    *
# * (at your option) any later version.                                  *
# *                                                                      *
# * This program is distributed in the hope that it will be useful,      *
# * but WITHOUT ANY WARRANTY; without even the implied warranty of       *
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        *
# * GNU General Public License for more details.                         *
# *                                                                      *
# * You should have received a copy of the GNU General Public License    *
# * along with this program.  If not, see <http://www.gnu.org/licenses/>.*
# ************************************************************************

runtest="yes";

if [ "x$1" = "x--do-cleanup" ]; then
  runtest="no";
fi

echo "# [ to execute the cleaning of logs+spool dirs give '--do-cleanup' as option ] ...";

ECHO="echo"

if [ "$runtest" = "no" ]; then
  ECHO=""
fi

echo "# Cleaning /var/log/eos/ ..."
$ECHO rm -rf /var/log/eos/* 2> /dev/null
echo "# Cleaning /var/spool/eos/ ..."
$ECHO rm -rf /var/spool/eos/* 2> /dev/null


