#!/bin/bash
# ----------------------------------------------------------------------
# File: eos-mgm-clean
# Author: Andreas-Joachim Peters - CERN
# ----------------------------------------------------------------------

# ************************************************************************
# * EOS - the CERN Disk Storage System                                   *
# * Copyright (C) 2011 CERN/Switzerland                                  *
# *                                                                      *
# * This program is free software: you can redistribute it and/or modify *
# * it under the terms of the GNU General Public License as published by *
# * the Free Software Foundation, either version 3 of the License, or    *
# * (at your option) any later version.                                  *
# *                                                                      *
# * This program is distributed in the hope that it will be useful,      *
# * but WITHOUT ANY WARRANTY; without even the implied warranty of       *
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        *
# * GNU General Public License for more details.                         *
# *                                                                      *
# * You should have received a copy of the GNU General Public License    *
# * along with this program.  If not, see <http://www.gnu.org/licenses/>.*
# ************************************************************************
runtest="yes";

if [ "x$1" = "x--do-cleanup" ]; then
  runtest="no";
fi

echo "# [ to execute the cleaning of the MGM give '--do-cleanup' as option ] ...";

if [ "$runtest" = "no" ]; then
 echo "# Cleaning /var/eos ..."
 rm -rf /var/eos/*
 echo "# Removing /etc/xrd.cf.mgm /etc/xrd.cf.mq ..."
 rm -rf /etc/xrd.cf.mgm /etc/xrd.cf.mq
 echo "# Removing /etc/sysconfig/eos ..."
 rm -rf /etc/sysconfig/eos
 echo "# Removing /var/log/eos/mgm/ /var/log/eos/mq/ ..."
 rm -rf /var/log/eos/mgm /var/log/eos/mq/
 echo "# Removing /var/spool/eos/mgm /var/spool/eos/mq ...
 rm -rf /var/spool/eos/mgm /var/spool/eos/mq
fi


