#!/bin/bash
# ----------------------------------------------------------------------
# File: eos-mdreport
# Author: Andreas-Joachim Peters - CERN
# ----------------------------------------------------------------------

# ************************************************************************
# * EOS - the CERN Disk Storage System                                   *
# * Copyright (C) 2024 CERN/Switzerland                                  *
# *                                                                      *
# * This program is free software: you can redistribute it and/or modify *
# * it under the terms of the GNU General Public License as published by *
# * the Free Software Foundation, either version 3 of the License, or    *
# * (at your option) any later version.                                  *
# *                                                                      *
# * This program is distributed in the hope that it will be useful,      *
# * but WITHOUT ANY WARRANTY; without even the implied warranty of       *
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        *
# * GNU General Public License for more details.                         *
# *                                                                      *
# * You should have received a copy of the GNU General Public License    *
# * along with this program.  If not, see <http://www.gnu.org/licenses/>.*
# ************************************************************************

# just check if we have an MGM locally, otherwise we don't do anything
timeout 5 eos root://localhost whoami >& /dev/null || exit 0
eos root://localhost ns stat -a -n -m > /var/eos/md/mdstats.tmp
if [ -e "/var/eos/md/mdstats.0" ]; then
    cp /var/eos/md/mdstats.0 /var/eos/md/mdstats.1
fi
mv /var/eos/md/mdstats.tmp /var/eos/md/mdstats.0


