#!/bin/bash
# ----------------------------------------------------------------------
# File: eosadmin
# Author: Andreas-Joachim Peters - CERN
# ----------------------------------------------------------------------

# ************************************************************************
# * EOS - the CERN Disk Storage System                                   *
# * Copyright (C) 2011 CERN/Switzerland                                  *
# *                                                                      *
# * This program is free software: you can redistribute it and/or modify *
# * it under the terms of the GNU General Public License as published by *
# * the Free Software Foundation, either version 3 of the License, or    *
# * (at your option) any later version.                                  *
# *                                                                      *
# * This program is distributed in the hope that it will be useful,      *
# * but WITHOUT ANY WARRANTY; without even the implied warranty of       *
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        *
# * GNU General Public License for more details.                         *
# *                                                                      *
# * You should have received a copy of the GNU General Public License    *
# * along with this program.  If not, see <http://www.gnu.org/licenses/>.*
# ************************************************************************

if [[ -r /etc/sysconfig/eos ]]; then
 # Handle old SysV scripts
 . /etc/sysconfig/eos
elif [[ -r /etc/sysconfig/eos_env ]]; then
 # Handle systemd environment script
 set -a
 . /etc/sysconfig/eos_env
 set +a
fi

NORMAL=$(tput sgr0)
RED=$(tput setaf 1)

function red() {
    echo -e "$RED$*$NORMAL"
}

# Try to guess the value of EOS_MGM_URL if not exit.
if [[ -z "${EOS_MGM_URL}" ]]; then
  if [[ -n "${EOS_MGM_ALIAS}" ]]; then
    EOS_MGM_URL=root://${EOS_MGM_ALIAS}
  fi
fi

if [[ -z "${EOS_MGM_URL}" ]]; then
  red "EOS_MGM_URL is not defined. Please review the sysconfig script."
  exit 1;
fi

export EOS_MGM_URL
export XrdSecPROTOCOL=sss
eos "$@"
