# eos-chart/server
# --set global.repository=$IMAGE_REPO --set global.tag=$IMAGE_TAG --set fst.replicaCount=8 --set fst.selfRegister.groupsize=8 --set fst.selfRegister.groupmod=1 \
# --set mgm.kerberos.enable=true --set mgm.kerberos.admin_princ.name=$TEST_ADMINPRINC_NAME --set mgm.kerberos.admin_princ.password=$TEST_ADMINPRINC_PASSWORD

global:
  repository: gitlab-registry.cern.ch/dss/eos/eos-ci
  tag: "--set-string $IMAGE_TAG"
  keytab:
    # matches the fusex chart value
    secret: eos-sss-keytab
  http:
    enabled: true
  securityContext:
    privileged: true
    allowPrivilegeEscalation: true

qdb:
  replicaCount: 1

fst:
  replicaCount: 15
  minFsSizeGb: 1
  selfRegister:
    groupsize: 7
    groupmod: 2
  extraEnv:
    - name: EOS_FST_TESTING
      value: "1"
    - name: EOS_FST_HTTP_PORT
      value: "8443"

mgm:
  kerberos:
    enabled: true
    clientConfig:
      # matches the default kerberos.fullname from the kuberos chart
      configMap: kuberos-kuberos-krb5-config
    adminPrinc:
      name: "--set $TEST_ADMINPRINC_NAME"
      password: "--set $TEST_ADMINPRINC_PASSWORD"
