#! /bin/bash

BRANCH=$1
BUILD_TYPE=$2
PATH_PREFIX=$3

STORAGE_PATH_CC7=${PATH_PREFIX}/${BRANCH}/${BUILD_TYPE}/el-7/x86_64
mkdir -p $STORAGE_PATH_CC7
cp cc7_artifacts/* $STORAGE_PATH_CC7
createrepo -q $STORAGE_PATH_CC7

STORAGE_PATH_SLC6=${PATH_PREFIX}/${BRANCH}/${BUILD_TYPE}/el-6/x86_64
mkdir -p $STORAGE_PATH_SLC6
cp slc6_artifacts/* $STORAGE_PATH_SLC6
createrepo -q $STORAGE_PATH_SLC6

STORAGE_PATH_FCRH=${PATH_PREFIX}/${BRANCH}/${BUILD_TYPE}/fc-rawhide/x86_64
mkdir -p $STORAGE_PATH_FCRH
cp fcrawhide_artifacts/* $STORAGE_PATH_FCRH
createrepo -q $STORAGE_PATH_FCRH

STORAGE_PATH_FCOLD=${PATH_PREFIX}/${BRANCH}/${BUILD_TYPE}/fc-25/x86_64
mkdir -p $STORAGE_PATH_FCOLD
cp fcold_artifacts/* $STORAGE_PATH_FCOLD
createrepo -q $STORAGE_PATH_FCOLD

STORAGE_PATH_MACOS=${PATH_PREFIX}/${BRANCH}/${BUILD_TYPE}/osx/x86_64
mkdir -p $STORAGE_PATH_MACOS
cp osx_artifacts/* $STORAGE_PATH_MACOS

exit 0
