#!/bin/bash
#
# Init file for the Gridftp server
#
# chkconfig: 2345 95 15
# description: Globus gridftp server with XRootD/DSI plugin
#
# processname: globus-gridftp-server
# config: /etc/sysconfig/xrootd-gridftp-server


# source function library
. /etc/rc.d/init.d/functions


# source sysconfig file
if [ -f /etc/sysconfig/xrootd-gridftp-server ]; then
    . /etc/sysconfig/xrootd-gridftp-server
fi

export CSEC_MECH=ID

###############  Standard Globus configuration  ######################

if [ -f /etc/sysconfig/globus ]; then
    . /etc/sysconfig/globus
fi

if [ -n "$GLOBUS_TCP_PORT_RANGE" ]; then
  export GLOBUS_TCP_PORT_RANGE
fi

if [ -n "$GLOBUS_UDP_PORT_RANGE" ]; then
  export GLOBUS_UDP_PORT_RANGE
fi

######################################################################

RETVAL=0

# Defaults

prog="globus-gridftp-server"

ftpd=/usr/sbin/globus-gridftp-server
port_standalone=${GLOBUS_GRIDFTP_PORT:-2811}
port_frontend=$port_standalone
port_backend=${GLOBUS_GRIDFTP_PORT_BACKEND:-7001}
log=${GLOBUS_GRIDFTP_LOG:-/var/log/xrootd/gridftp/$prog.log}
debuglog=${GLOBUS_GRIDFTP_DEBUGLOG:-/var/log/xrootd/gridftp/$prog-debug.log}
debugloglevel=${GLOBUS_GRIDFTP_DEBUGLOG_LEVEL:-warn,error,info}
pid_file=/var/run/$prog.pid
lockfile=/var/lock/subsys/$prog
user=""
options=${GLOBUS_GRIDFTP_OPTIONS:-""}


# -S  stand alone mode
# -p  port number
# -Z  Globus logging
#
# Running as a non-root user:
#
# -Q  Don't use pid files since you don't have write access to them ( /var/run )
# -W  Don't record logins in wtmp (you don't have write permissions)
#

if [ ! -d "/var/log/xrootd/gridftp" ]; then
	mkdir -p /var/log/xrootd/gridftp
	echo create /var/log/xrootd/gridftp
fi

options2=""
if [ -z "$options" ]; then
    options_standalone=" -S -p $port_standalone -log-module stdio -logfile $debuglog -log-level $debugloglevel -log-transfer $log -dsi xrootd -threads 1"
    options_frontend=" -S -p $port_frontend -log-module stdio -logfile ${debuglog}.frontend -log-level $debugloglevel -log-transfer ${log}.frontend -dsi xrootd -threads 1"
    options_backend=" -S -dn -p $port_backend -log-module stdio -logfile ${debuglog}.backend -log-level $debugloglevel -log-transfer ${log}.backend -dsi xrootd -threads 1"
    case "$XROOTD_DSI_SERVER_ROLE" in
        standalone)
            options="$options_standalone"
            ;;         
        frontend)
            options="$options_frontend"
            ;;
        backend)
            options="$options_backend"
            ;;
        split)
            options="$options_frontend"
            options2="$options_backend"
            export XROOTD_DSI_SERVER_ROLE="frontend"
            ;;
        *)
            echo 'invalid value for XROOTD_DSI_SERVER_ROLE. valid values are "standalone","frontend","backend","split"'
            RETVAL=1;
            ;;
    esac  
fi

start()
{
    export XRD_ENABLEFORKHANDLERS=1
    if [ "$RETVAL" == 0 ]
    then
		echo -n "Starting $prog:"
        if test "x$user" = "x" ; then
    		daemon "$ftpd $options"
            if [ $? = 0 ] && [ "x$options2" != "x" ] 
            then
                export XROOTD_DSI_SERVER_ROLE="backend"
    	    	daemon "$ftpd $options2"
    		fi
        else
          	daemon "--user $user $ftpd -Q -W $options"
            if [ $? = 0 ] && [ "x$options2" != "x" ]  
            then
                export XROOTD_DSI_SERVER_ROLE="backend"
    	    	daemon "--user $user $ftpd -Q -W $options2"
    		fi
        fi
    fi
	RETVAL=$?
	[ "$RETVAL" = 0 ] && touch $lockfile
	echo
}

stop()
{
	echo -n "Stopping $prog:"
	killproc $ftpd -TERM
	RETVAL=$?
	[ "$RETVAL" = 0 ] && rm -f $lockfile
	echo
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		start
		;;
	condrestart)
		if [ -f $lockfile ] ; then
			stop
			# avoid race
			sleep 3
			start
		fi
		;;
	status)
		status $ftpd
		RETVAL=$?
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload|condrestart|status}"
		RETVAL=1
esac

exit $RETVAL
