// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Shaping.proto

#include "Shaping.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace Shaping {
template <typename>
PROTOBUF_CONSTEXPR received_DataEntry_DoNotUse::received_DataEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct received_DataEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR received_DataEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~received_DataEntry_DoNotUseDefaultTypeInternal() {}
  union {
    received_DataEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 received_DataEntry_DoNotUseDefaultTypeInternal _received_DataEntry_DoNotUse_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR received::received(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.data_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct receivedDefaultTypeInternal {
  PROTOBUF_CONSTEXPR receivedDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~receivedDefaultTypeInternal() {}
  union {
    received _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 receivedDefaultTypeInternal _received_default_instance_;
}  // namespace Shaping
static ::_pb::Metadata file_level_metadata_Shaping_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_Shaping_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Shaping_2eproto = nullptr;
const ::uint32_t TableStruct_Shaping_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::Shaping::received_DataEntry_DoNotUse, _has_bits_),
    PROTOBUF_FIELD_OFFSET(::Shaping::received_DataEntry_DoNotUse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::Shaping::received_DataEntry_DoNotUse, key_),
    PROTOBUF_FIELD_OFFSET(::Shaping::received_DataEntry_DoNotUse, value_),
    0,
    1,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::Shaping::received, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::Shaping::received, _impl_.data_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, 10, -1, sizeof(::Shaping::received_DataEntry_DoNotUse)},
        { 12, -1, -1, sizeof(::Shaping::received)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::Shaping::_received_DataEntry_DoNotUse_default_instance_._instance,
    &::Shaping::_received_default_instance_._instance,
};
const char descriptor_table_protodef_Shaping_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\rShaping.proto\022\007Shaping\"b\n\010received\022)\n\004"
    "data\030\001 \003(\0132\033.Shaping.received.DataEntry\032"
    "+\n\tDataEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\001"
    ":\0028\001b\006proto3"
};
static ::absl::once_flag descriptor_table_Shaping_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Shaping_2eproto = {
    false,
    false,
    132,
    descriptor_table_protodef_Shaping_2eproto,
    "Shaping.proto",
    &descriptor_table_Shaping_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_Shaping_2eproto::offsets,
    file_level_metadata_Shaping_2eproto,
    file_level_enum_descriptors_Shaping_2eproto,
    file_level_service_descriptors_Shaping_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Shaping_2eproto_getter() {
  return &descriptor_table_Shaping_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Shaping_2eproto(&descriptor_table_Shaping_2eproto);
namespace Shaping {
// ===================================================================

received_DataEntry_DoNotUse::received_DataEntry_DoNotUse() {}
received_DataEntry_DoNotUse::received_DataEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void received_DataEntry_DoNotUse::MergeFrom(const received_DataEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata received_DataEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Shaping_2eproto_getter, &descriptor_table_Shaping_2eproto_once,
      file_level_metadata_Shaping_2eproto[0]);
}
// ===================================================================

class received::_Internal {
 public:
};

received::received(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Shaping.received)
}
received::received(const received& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  received* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_.data_)*/{}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.data_.MergeFrom(from._impl_.data_);
  // @@protoc_insertion_point(copy_constructor:Shaping.received)
}

inline void received::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      /*decltype(_impl_.data_)*/{::_pbi::ArenaInitialized(), arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

received::~received() {
  // @@protoc_insertion_point(destructor:Shaping.received)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void received::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.data_.~MapField();
}

void received::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void received::Clear() {
// @@protoc_insertion_point(message_clear_start:Shaping.received)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* received::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // map<string, double> data = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.data_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* received::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Shaping.received)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, double> data = 1;
  if (!this->_internal_data().empty()) {
    using MapType = ::_pb::Map<std::string, double>;
    using WireHelper = received_DataEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_data();
    auto check_utf8 = [](const MapType::value_type& entry) {
      (void)entry;
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          entry.first.data(), static_cast<int>(entry.first.length()),
 ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "Shaping.received.data");
    };

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterPtr<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Shaping.received)
  return target;
}

::size_t received::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Shaping.received)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, double> data = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_data_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, double >::const_iterator
      it = this->_internal_data().begin();
      it != this->_internal_data().end(); ++it) {
    total_size += received_DataEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData received::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    received::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*received::GetClassData() const { return &_class_data_; }


void received::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<received*>(&to_msg);
  auto& from = static_cast<const received&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Shaping.received)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.data_.MergeFrom(from._impl_.data_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void received::CopyFrom(const received& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Shaping.received)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool received::IsInitialized() const {
  return true;
}

void received::InternalSwap(received* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.data_.InternalSwap(&other->_impl_.data_);
}

::PROTOBUF_NAMESPACE_ID::Metadata received::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Shaping_2eproto_getter, &descriptor_table_Shaping_2eproto_once,
      file_level_metadata_Shaping_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Shaping
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Shaping::received_DataEntry_DoNotUse*
Arena::CreateMaybeMessage< ::Shaping::received_DataEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Shaping::received_DataEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::Shaping::received*
Arena::CreateMaybeMessage< ::Shaping::received >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Shaping::received >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
